version: '3'

volumes:
  db-data:
  db-socket: 

services:
  db:
    container_name: db
    image: mysql:8.0.30
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql/
      - db-socket:/var/run/mysqld/
    ports:
      - 3307:3306
    restart: always

  backend:
    container_name: backend
    depends_on:
      - db
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    entrypoint: ["/bin/bash", "-c"]
    command: 
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0:8000
    volumes:
      - ./backend/:/app/
      - ./backend/.collected_static/:/app/.collected_static/
      - db-socket:/var/run/mysqld/
    ports:
      - '8000:8000'
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
