FROM python:3.10.4

WORKDIR /app/

# Copy package list from context folder to image
ADD requirements.txt .
# Install packages
RUN pip install -r requirements.txt

# (Optional) Remove stdout delay
ENV PYTHONUNBUFFERED 0