# Generated by Django 4.1.2 on 2023-01-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyrecord",
            name="xp_accumulate",
            field=models.IntegerField(),
        ),
    ]
