# Generated by Django 4.0.6 on 2022-09-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_growth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='estimate_unit',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='habit',
            name='growth_amount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='temporary_progress',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='today_goal',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='today_progress',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
