# Generated by Django 4.0.6 on 2022-09-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_estimate_unit_alter_habit_growth_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='growth_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='last_done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='paused_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='temporary_progress',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='today_goal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='today_progress',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
