# Generated by Django 4.0.6 on 2022-09-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_growth_amount_alter_habit_last_done_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='growth_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='temporary_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='today_goal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='today_progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
